#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.45.0
#FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.45.0
#FROM gcr.io/google.com/cloudsdktool/cloud-sdk:302.0.0-slim
#FROM docker.io/nginx:1.16.1
#FROM nginx
#FROM ghcr.io/llm-d/llm-d-cuda:v0.3.1
#FROM minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
#FROM registry.k8s.io/gateway-api/echo-basic:v1.5.1
FROM kostiscodefresh/summer-of-k8s-app:v1
#FROM kostiscodefresh/summer-of-k8s-app:v2
