#FROM gcr.io/knative-releases/knative.dev/serving/cmd/activator
#FROM gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
#FROM gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
#FROM gcr.io/knative-releases/knative.dev/serving/cmd/webhook
#FROM gcr.io/knative-releases/knative.dev/serving/cmd/controller
#FROm gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
#FROM gcr.io/knative-releases/knative.dev/serving/cmd/queue
FROM gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:d479c6879b4e5429745f96026679e6267e7b5a8cfc7dc8e334a64d4241cd5c1a
